Repository openshift/node-observability-operator, pull requests merged in 2022-04, with the labels that each got.

#24 updates node-observability Operator using a custom index image on OperatorHub procedure
  README.md
Labels: lgtm, approved

#29 Activate gosec in golangci
  .golangci.yaml
  pkg/operator/controller/test/vars.go
Labels: lgtm, approved

#31 Add NodeObservabilityMachineConfig CR in NodeObservabilityCSV
  bundle.Dockerfile
  bundle/manifests/node-observability-operator.clusterserviceversion.yaml
  bundle/manifests/nodeobservability.olm.openshift.io_nodeobservabilitymachineconfigs.yaml
  bundle/manifests/nodeobservability.olm.openshift.io_nodeobservabilityruns.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/node-observability-operator.clusterserviceversion.yaml
  pkg/operator/controller/machineconfig/controller.go
  pkg/operator/controller/machineconfig/crio.go
  pkg/operator/controller/machineconfig/kubelet.go
Labels: lgtm, approved

#30 Add TLS and token based auth
  cmd/node-observability-operator/main.go
  config/manager/manager.yaml
  config/rbac/role.yaml
  pkg/operator/controller/nodeobservability/controller.go
  pkg/operator/controller/nodeobservability/daemonset.go
  pkg/operator/controller/nodeobservability/rbac.go
  pkg/operator/controller/nodeobservability/service.go
  pkg/operator/controller/nodeobservabilityrun/controller.go
Labels: docs-approved, px-approved, qe-approved, lgtm, approved

#36 Update in e2e tests to fix some minor bugs and image reference
  Makefile
  bundle/manifests/node-observability-operator.clusterserviceversion.yaml
  bundle/manifests/node-observability-operator_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/samples/nodeobservability_v1alpha1_nodeobservability-all.yaml
  pkg/operator/controller/nodeobservability/controller.go
  pkg/operator/controller/nodeobservability/controller_test.go
  pkg/operator/controller/nodeobservability/daemonset.go
  pkg/operator/controller/nodeobservability/rbac.go
  pkg/operator/controller/nodeobservability/rbac_test.go
  pkg/operator/controller/nodeobservability/service.go
  pkg/operator/controller/nodeobservability/simulate-error-schema.go
  test/e2e/nodeobservability_test.go
  test/e2e/nodeobservabiltiyrun_test.go
  test/e2e/util.go
Labels: docs-approved, px-approved, qe-approved, lgtm, approved

#37 Use correct label selector
  config/samples/nodeobservability_v1alpha1_nodeobservability.yaml
Labels: docs-approved, px-approved, qe-approved, lgtm, approved

#38 Fix bundle generation
  Makefile
  bundle/manifests/node-observability-operator-auth-proxy_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/node-observability-operator-auth-proxy_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/node-observability-operator-auth-proxy_v1_service.yaml
  bundle/manifests/node-observability-operator.clusterserviceversion.yaml
  bundle/manifests/node-observability-operator_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/node-observability-operator_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  tools/tools.go
Labels: docs-approved, px-approved, tide/merge-method-squash, qe-approved, lgtm, approved

#39 Fix security audit shortcomings
  Dockerfile
  Makefile
  bundle/manifests/node-observability-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  hack/verify-bundle.sh
  hack/verify-gofmt.sh
  hack/verify-olm.sh
  pkg/operator/controller/nodeobservability/controller.go
Labels: docs-approved, px-approved, tide/merge-method-squash, qe-approved, lgtm, approved
